test
Listoc/tinkoff-java-course pull request #8
Opened 2023-11-16 10:46 UTC by Listoc

2023-12-04 14:33 UTC, sn1tr0n requested changes
В целом, очень неплохая работа. Основные замечания: 
1. неинформативные exceptions
2. проверку на ``null`` некоторых переменных можно оформить через аннотацию ``@NotNull``

Можешь поправить замечания (minor править необязательно, это скорее рекомендации), тогда поставлю максимум. Также, если есть вопросы/не согласен с комментариями, можешь пинговать меня в телегу или писать тут в комментах.

2/3

2023-12-04 14:33 UTC, sn1tr0n commented on src/main/java/edu/hw6/task1/DiskMap.java
> +        try (var writer = new BufferedWriter(new FileWriter(FILE_NAME))) {
Классы из пакета java.io.* работают с файлами в стандартной кодировке ОС, на которой запущена JVM. Иногда, полагаясь на это, можно сильно проиграть) (передаём привет Windows и CP866)

Лучше добавить StandardCharsets.UTF_8 в аргумент конструктора FileWriter

2023-12-04 14:33 UTC, sn1tr0n commented on src/main/java/edu/hw6/task1/DiskMap.java
> +            while (reader.ready()) {
Лучше читать до ``reader.readLine() == null``, тк ``.ready()`` под капотом блокирующий (как и ``readLine()``). Таким образом, на каждой итерации ты берёшь блокировку сначала на ``ready()``, а потом на ``readLine()``, что дорого

2023-12-04 14:33 UTC, sn1tr0n commented on src/main/java/edu/hw6/task1/DiskMap.java
> +                    throw new IOException();
Лучше сообщить пользователю, что пошло не так)

2023-12-04 14:33 UTC, sn1tr0n commented on src/main/java/edu/hw6/task1/DiskMap.java
> +                writer.write(key + ':' + map.get(key));
душный minor: можно не конкатенировать строку, а сразу пробрасывать в буфер writer'a через цепочку append();

2023-12-04 14:33 UTC, sn1tr0n commented on src/main/java/edu/hw6/task1/DiskMap.java
> +            for (var key : map.keySet()) {
Итерироваться можно сразу по .entrySet(), чтобы ещё раз не искать .get(key)

2023-12-04 14:33 UTC, sn1tr0n commented on src/main/java/edu/hw6/task5/HackerNews.java
> +           var pattern = Pattern.compile("(\"title\":\"([^\"]*)\")");
Каждый раз компилировать регулярку дорого --- под капотом там строится конечный автомат. Лучше создать её как статическую переменную

2023-12-04 14:33 UTC, sn1tr0n commented on src/main/java/edu/hw6/task6/PortsChecker.java
> +                serviceName = serviceName == null ? "Undefined" : serviceName;
SERVICES_BY_PORTS.getOrDefault()

2023-12-04 14:33 UTC, sn1tr0n commented on src/main/java/edu/hw6/task6/PortsChecker.java
> +        getPorts(0, 49151);
Лучше вытащить min, max порты как константы; так будет читабельнее

2023-12-04 14:33 UTC, sn1tr0n commented on src/main/java/edu/hw6/task6/PortsChecker.java
> +        for (int port = startPort; port < endPort + 1; ++port) {
minor: В Java принято в циклах использовать постфиксный инкремент ``port++``

PS: тут всё-таки не C++, разницы в перфомансе нету)

2023-12-04 14:33 UTC, snitron commented on src/main/java/edu/hw6/task3/AbstractFilter.java
> +        return (Path path) -> path.getFileName().toString().matches(str);
getFileName() может вернуть null

2023-12-04 14:33 UTC, snitron commented on src/main/java/edu/hw6/task3/AbstractFilter.java
> +                var firstByte = Integer.toHexString(Files.readAllBytes(path)[0] & 0xff);
Вычитать весь файл, чтобы получить первый байт --- звучит не очень

2023-12-04 14:33 UTC, snitron commented on src/main/java/edu/hw6/task2/ClonerUtil.java
> +        var split = path.getFileName().toString().split("\\.");
душный minor:

Вот тут не уверен, что это правильная логика. Почему "a.b.c" должно копироваться как "a.b - (копия).c"? С "my-best-archive.tar.gz" наверное мы всё же хотим, чтобы получилось "my-best-archive - (копия).tar.gz"


Но даже если делать так, то можно поискать по строке первые и последние вхождения '.', и за один проход собрать нужную строку, без лишних аллокаций от ``split()``.


Подумай, как лучше сделать

2023-12-04 14:33 UTC, snitron commented on src/main/java/edu/hw6/task1/DiskMap.java
> +        try (var reader = new BufferedReader(new FileReader(FILE_NAME))) {
same про кодировку

2023-12-04 14:33 UTC, snitron commented on src/main/java/edu/hw6/task5/HackerNews.java
> +        try (var client = HttpClient.newHttpClient()) {
minor: get запрос к серверу можно вынести в общую функцию, тем самым будет меньше копипасты

2023-12-04 19:48 UTC, Listoc commented on src/main/java/edu/hw6/task2/ClonerUtil.java
> +        var split = path.getFileName().toString().split("\\.");
Как-то сразу не подумал об этой логике, сделал по первому варианту

2023-12-05 07:13 UTC, snitron requested changes

2023-12-05 07:13 UTC, snitron commented on src/main/java/edu/hw6/task3/AbstractFilter.java
> +                firstByteHex = Integer.toHexString(reader.read() & 0xff);
А почему ты уверен, что read() точно что-то прочитал?)

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/BufferedReader.html#read()

2023-12-05 07:13 UTC, snitron commented on src/main/java/edu/hw6/task3/AbstractFilter.java
> +                for (var el : bytes) {
Плюс ты держишь файловый дескриптор открытым на время проведения каких-то вычислений. Тут это, конечно, не страшно, но в другой ситуации может повредить (например, если вместо цикла написать тут http-запрос)

2023-12-05 07:13 UTC, snitron commented on src/main/java/edu/hw6/task3/AbstractFilter.java
> +                    if (Integer.toHexString(el & 0xff).equals(firstByteHex)) {
И ещё не понял, зачем сравнивать hex-строки, если можно просто сравнивать инты?)

2023-12-05 07:13 UTC, snitron commented on src/main/java/edu/hw6/task2/ClonerUtil.java
> +        for (var ch : fileNameArray) {
minor: String#indexOf(), String#lastIndexOf()

2023-12-05 07:13 UTC, snitron commented on src/test/java/edu/hw6/Task2Test.java
> +    void clear() throws IOException {
minor: чтобы руками не стирать так файлы (а вдруг прога вообще по-другому файл назовёт, и мы его не почистим?), можно создать папку а-ля ``test_tmp`` и потом просто удалять её. Тоже решение не без греха, но имхо красивее

2023-12-05 09:22 UTC, Listoc commented on src/main/java/edu/hw6/task3/AbstractFilter.java
> +                firstByteHex = Integer.toHexString(reader.read() & 0xff);
Вообще я исходил из логики, что если вернулась -1, то оно дальше проверку в цикле не пройдет

2023-12-05 09:32 UTC, Listoc commented on src/main/java/edu/hw6/task3/AbstractFilter.java
> +                    if (Integer.toHexString(el & 0xff).equals(firstByteHex)) {
Хороший вопрос, я тогда почему-то решил, что иначе не смогу сравнить из-за того, что байт читал, а не инт

2023-12-05 09:37 UTC, snitron commented on src/main/java/edu/hw6/task3/AbstractFilter.java
> +                firstByteHex = Integer.toHexString(reader.read() & 0xff);
Да, но возможно мы хотим `-1` обрабатывать как-то иначе, всё таки это сигнал о другом поведении ридера

2023-12-05 09:38 UTC, snitron commented
3/3

2023-12-05 09:38 UTC, snitron approved these changes
3/3

2023-12-05 09:40 UTC, merged